type User {
	id: ID
	name: String
	avatar: String
	email: String
}

# Pagination types
type PageInfo {
	hasPreviousPage: Boolean!
	hasNextPage: Boolean!
	startCursor: String
	endCursor: String
}

type UserEdge {
	cursor: String!
	node: User!
}

type UserConnection {
	edges: [UserEdge!]!
	pageInfo: PageInfo!
}

# Root query
type Query {
	users: [User]
	searchUsers(first: Int!, after: String!): UserConnection!
}
